config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	root to: 'staticpages#home'
  get 'clubs/index', to: 'clubs#index', as: 'club'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

	validates :first_name, presence: true, uniqueness: {case_sensitive: false}, format: {with: /\A[a-zA-Z0-9 _\.]*\z/}
	validates :last_name, presence: true, uniqueness: {case_sensitive: false}, format: {with: /\A[a-zA-Z0-9 _\.]*\z/}
	validates :email, presence: true, uniqueness: true

  devise :database_authenticatable, :registerable,
		 :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
	end

end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  def index
	if (user_signed_in? == false)
		flash[:danger] = 'Sign up or login to access of the private club !'
		redirect_to root_path
	end
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/clubs/index.html.erb
<div class="container">
	<h2> The Private Club </h2></br>
	<table class="table table-striped">
  		<tr>
    		<th>First name</th>
   			<th>Last name</th>
    		<th>Email</th>
  		</tr>
 
  		<% User.all.each do |user|%> 
    		<tr>
      			<td><%= user.first_name %></td>
      			<td><%= user.last_name %></td>
      			<td><%= user.email %></td>
    		</tr>
  		<% end %>
	</table>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%=root_path%>">Private club welcome !</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Home", root_path, class: "nav-item nav-link" %>
      <% if user_signed_in? %>
        <%= link_to 'Private club', club_path, class: "nav-item nav-link" %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
      <% else %>
        <%= link_to 'Login', new_user_session_path, class: "nav-item nav-link" %>
        <%= link_to 'Sign up', new_user_registration_path, class: "nav-item nav-link" %>
      <% end %>
    </div>
  </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private club</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!-- Bootstrap navbar-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'layouts/header' %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

  </body>

</html>

app/views/staticpages/home.html.erb
<div class="jumbotron">
	<div class="container">
    	<h1>Hey, you're on the private club page !</h1>
    	<br/>
    	<% if user_signed_in? %>
	    		<h3> To join the private club and see other users, click <%= link_to 'here', club_path, class: 'btn btn-info active' %></h3>
    	<% else %>
    		<h2>You need to be login to get access to the private club !</h2></br>
    		<h3>So <%= link_to 'Login', new_user_session_path, class: 'btn btn-info active' %> or <%= link_to 'Signup', new_user_registration_path, class: 'btn btn-info active' %></h3>
    	<% end %>
  	</div>
</div>